### ISSUE TITLE
Support for swift 3 

### ISSUE THREAD

**Issue by Nautiyalsachin** [trailbehind/TBOOMDetector#5]
can you help me out here. I am using the latest frameworks for both Crashlytics and Fabric but still I am unable to include it in my project. Thank you for the help!

**Comment by JesseCrocker** [comment]
Can you elaborate on what the problem is?

**Comment by Nautiyalsachin** [comment]
My app is getting out of memory error for iPad and iPods, I am using a table view for showing multiple photos and when I am scrolling it fast its getting disconnected from xCode. Don't know what is the problem here. I want to use this library for debug that problem but unable to do so. Should I have to include the two files in my code as using bridging header or is it included into the Fabric library. Let me know if still I am unable to explain it.

**Comment by Nautiyalsachin** [comment]
Sorry, I didn't see you have included the file in your AppDelegate my bad.I will include it and let you know soon.

**Comment by JesseCrocker** [comment]
You need to initialize TBOOMDetector as indicated in the README.md file.
